### PR TITLE
Update Scala2 version to 2.13.12

### PR DESCRIPTION
**Pull request by tiagniuk**

### CODE REVIEW

**Comment by xuwei-k** [comment]
https://github.com/scala/scala3-cross.g8/actions/runs/6449647849/job/17509841333?pr=89#step:3:13

```
CLA check for tiagniuk failed
Please sign the Scala CLA to contribute to the Scala compiler.
Go to https://www.lightbend.com/contribute/cla/scala and then
comment on the pull request to ask for a new check.
```

**Comment by SethTisue** [comment]
@tiagniuk mind signing the CLA?

**Comment by tiagniuk** [comment]
Apologies, I haven't had much time recently to thoroughly read the document and understand the implications of signing it. I'll close the PR.

**Comment by SethTisue** [comment]
okay. I've submitted #93

**Pull request closed without merging**
